### PR TITLE
Added Arduino.h import to allow use of delay(). Fixes #5

### LINKED ISSUE #5: SI1145 fails to compile with esphome 2022.8.1
Not sure when this stopped working, but when I try to include the SI1145 external component, I get this compilation error:

```
src/esphome/components/si1145/si1145.cpp: In member function 'virtual void esphome::si1145::SI1145Component::update()':
src/esphome/components/si1145/si1145.cpp:108:11: error: 'delay' was not declared
 in this scope
   delay(20);
           ^
src/esphome/components/si1145/si1145.cpp: In member function 'void esphome::si1145::SI1145Component::reset_()':
src/esphome/components/si1145/si1145.cpp:320:11: error: 'delay' was not declared in this scope
   delay(10);
           ^
```

Adding an `#import "Arduino.h"` to `si1145.cpp` fixes the problem.

### PR DESCRIPTION
**Pull request by squidpickles**
This appears to work fine with the latest esphome.

### CODE REVIEW

**Review by mc-gl89 — APPROVED** [review]

**Comment by squidpickles** [comment]
@mc-gl89 thanks for approving this!

I think you'll need to do the actual merging, too.
